api_version = "2026-01"

[[extensions]]
name = "Wholesale Discount"
handle = "wholesale-discount"
type = "function"
uid = "0a427c64-4a1a-41c7-f518-d05492f3994c91180ad4"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"
